# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bruteflow <bruteflow@student.42.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/03/31 18:22:26 by bruteflow         #+#    #+#              #
#    Updated: 2019/03/31 18:35:19 by bruteflow        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all :
	gcc -c main.c
	gcc main.o -o ft_display_file

clean:
	rm -f *.o

fclean: clean
	rm -f ft_display_file

re: fclean all